### ISSUE TITLE
Should not set /etc/hosts when using third party registry

### ISSUE THREAD

**Issue by davidwtf** [tkestack/tke#121]
**What happened**:
The IP address of registry's domain has been set into the `/etc/hosts` of each target machine when using third party registry.

**What you expected to happen**:
When using third party registry, the /etc/hosts should not be changed.

**How to reproduce it (as minimally and precisely as possible)**:
Use `--no-ui` and config `Config.registy.thirdParty` in the `conf/tke.json`.

**Anything else we need to know?**:
`EnsureRegistryHosts` called `Registry.UseTKE()` which just compare registry's domain with `docker.io`. It seems unreasonable.

Maybe `EnsureRegistryHosts` could  check if m.Registry.IP is empty, and in `initProviderConfig()` could avoid set Registry.IP when using third party registry.

**Environment**:
- TKE version: v1.0.1
- Global or business cluster:
- Kubernetes version (use `kubectl version`):
- Install addons:
- Others:

**Comment by QianChenglong** [comment]
Fixed in next version.

**Comment by davidwtf** [comment]
This problem still exists in v1.1.0. 
Please reopen it.
`initProviderConfig()` set the ip, please check.
